# Generated by Django 5.2.15 on 2026-07-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('INSTALLATION_STARTED', 'Installation Started'), ('WORK_IN_PROGRESS', 'Work in Progress'), ('HALFWAY_COMPLETED', 'Halfway Completed'), ('INSTALLATION_COMPLETED', 'Installation Completed')], default='SCHEDULED', max_length=50),
        ),
    ]
